require: 
 - rubocop-graphql
 - rubocop-rspec
 - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable

  Include:
    - 'config.ru'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
    - 'db/seeds.rb'

  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'

Layout/IndentationConsistency:
  EnforcedStyle: 'indented_internal_methods'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'db/*'
    - 'config/initializers/*.rb'
    - 'config/environments/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
    - 'config/environments/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/graphql_controller.rb'

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes